require conf/machine/raspberrypi5.conf

# Use the same kernel metadata "machine" as rpi5 (avoids looking for raspberrypi5-uboot-tpm/standard)
KMACHINE = "raspberrypi5"

# Provide a kernel defconfig fallback (this is what do_kernel_metadata is asking for)
KBUILD_DEFCONFIG = "bcm2712_defconfig"

# 1) Build + deploy the overlay dtbo into /boot/firmware/overlays/
RPI_KERNEL_DEVICETREE_OVERLAYS:append = " overlays/tpm-slb9670.dtbo"

# 2) Tell Raspberry Pi firmware to load it (DT passed onward to U-Boot too)
#RPI_EXTRA_CONFIG:append = "\ndtparam=spi=on\ndtoverlay=tpm-slb9670\ndtoverlay=tpm-uboot-compat\n"

# Ensure the overlay is built and deployed
EXTRA_IMAGEDEPENDS += "letstrust-tpm-overlay"
EXTRA_IMAGEDEPENDS += "letstrust-tpm-uboot-overlay"

# Syntax: "SourcePath;DestinationPath"
# We must specify that the source file is inside the 'overlays' folder in the deploy dir
IMAGE_BOOT_FILES:append = " overlays/letstrust-tpm.dtbo;overlays/letstrust-tpm.dtbo"
IMAGE_BOOT_FILES:append = " overlays/letstrust-tpm-uboot.dtbo;overlays/letstrust-tpm-uboot.dtbo"

RPI_EXTRA_CONFIG:append = "\ndtparam=spi=on\ndtoverlay=letstrust-tpm\ndtoverlay=letstrust-tpm-uboot\n"
